#!/usr/bin/env bash
# bootstrap_nullclaw_refactor.sh
# Creates a rebranded Cerberus codebase from upstream NullClaw.
# Non-destructive to upstream snapshot; output goes to runtime/cerberus-core by default.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UPSTREAM_REPO="${UPSTREAM_REPO:-https://github.com/nullclaw/nullclaw.git}"
UPSTREAM_REF="${UPSTREAM_REF:-main}"
UPSTREAM_DIR="${UPSTREAM_DIR:-${ROOT_DIR}/vendor/nullclaw-upstream}"
TARGET_DIR="${TARGET_DIR:-${ROOT_DIR}/runtime/cerberus-core}"
REFRESH_UPSTREAM=false

for arg in "$@"; do
  case "$arg" in
    --refresh-upstream) REFRESH_UPSTREAM=true ;;
    --upstream-ref=*)   UPSTREAM_REF="${arg#*=}" ;;
    --target=*)         TARGET_DIR="${arg#*=}" ;;
    --upstream-dir=*)   UPSTREAM_DIR="${arg#*=}" ;;
  esac
done

info() { printf '\033[0;34m[bootstrap]\033[0m %s\n' "$*"; }
ok()   { printf '\033[0;32m[bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[0;33m[bootstrap]\033[0m %s\n' "$*"; }
fail() { printf '\033[0;31m[bootstrap]\033[0m %s\n' "$*"; exit 1; }

if [[ ! -d "$UPSTREAM_DIR/.git" ]]; then
  info "Cloning upstream NullClaw"
  mkdir -p "$(dirname "$UPSTREAM_DIR")"
  git clone --depth 1 --branch "$UPSTREAM_REF" "$UPSTREAM_REPO" "$UPSTREAM_DIR"
elif $REFRESH_UPSTREAM; then
  info "Refreshing upstream snapshot from $UPSTREAM_REF"
  git -C "$UPSTREAM_DIR" fetch --depth 1 origin "$UPSTREAM_REF"
  git -C "$UPSTREAM_DIR" checkout --detach FETCH_HEAD
fi

if [[ ! -d "$UPSTREAM_DIR" ]]; then
  fail "Upstream directory not found: $UPSTREAM_DIR"
fi

mkdir -p "$(dirname "$TARGET_DIR")"
info "Copying upstream into target: $TARGET_DIR"
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete --exclude ".git/" "$UPSTREAM_DIR/" "$TARGET_DIR/"
else
  warn "rsync not found; using cp fallback"
  rm -rf "$TARGET_DIR"
  mkdir -p "$TARGET_DIR"
  cp -a "$UPSTREAM_DIR/." "$TARGET_DIR/"
  rm -rf "$TARGET_DIR/.git"
fi

if [[ -f "$TARGET_DIR/nullclaw.png" ]]; then
  mv "$TARGET_DIR/nullclaw.png" "$TARGET_DIR/cerberus.png"
fi

generated_ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

info "Rebranding text markers (NullClaw -> Cerberus)"
while IFS= read -r -d '' file; do
  perl -0pi -e 's/NULLCLAW/CERBERUS/g; s/NullClaw/Cerberus/g; s/nullclaw/cerberus/g' "$file"
done < <(
  grep -RIlZ \
    --exclude-dir=".git" \
    --exclude-dir="sqlite3" \
    --exclude="LICENSE" \
    --exclude="build.zig.zon2json-lock" \
    -E "nullclaw|NullClaw|NULLCLAW" "$TARGET_DIR"
)

# Zig package fingerprint changes when package identity changes.
# Keep the rebranded package fingerprint valid for Cerberus builds.
if [[ -f "$TARGET_DIR/build.zig.zon" ]]; then
  perl -0pi -e 's/\.fingerprint\s*=\s*0x[0-9a-fA-F]+,/.fingerprint = 0x871985ae8afeccc0,/g' "$TARGET_DIR/build.zig.zon"
fi

commit_sha="$(git -C "$UPSTREAM_DIR" rev-parse HEAD 2>/dev/null || printf "unknown")"
cat > "$TARGET_DIR/UPSTREAM.md" <<EOF
# Upstream Base

Cerberus runtime tree is derived from NullClaw upstream.

- repo: ${UPSTREAM_REPO}
- ref: ${UPSTREAM_REF}
- commit: ${commit_sha}
- generated_at_utc: ${generated_ts}

This file is generated by \`scripts/bootstrap_nullclaw_refactor.sh\`.
EOF

mkdir -p "$TARGET_DIR/scripts/compat"
cat > "$TARGET_DIR/scripts/compat/nullclaw" <<'EOF'
#!/usr/bin/env bash
# Backward-compatible command shim.
# Allows old scripts that still call `nullclaw` to execute Cerberus.

set -euo pipefail

bridge_env() {
  local old_var="$1"
  local new_var="$2"
  local old_val="${!old_var:-}"
  local new_val="${!new_var:-}"
  if [[ -n "$old_val" && -z "$new_val" ]]; then
    export "${new_var}=${old_val}"
  fi
}

# Legacy env -> Cerberus env bridge
bridge_env "NULLCLAW_PROVIDER" "CERBERUS_PROVIDER"
bridge_env "NULLCLAW_MODEL" "CERBERUS_MODEL"
bridge_env "NULLCLAW_TEMPERATURE" "CERBERUS_TEMPERATURE"
bridge_env "NULLCLAW_GATEWAY_PORT" "CERBERUS_GATEWAY_PORT"
bridge_env "NULLCLAW_GATEWAY_HOST" "CERBERUS_GATEWAY_HOST"
bridge_env "NULLCLAW_WORKSPACE" "CERBERUS_WORKSPACE"
bridge_env "NULLCLAW_ALLOW_PUBLIC_BIND" "CERBERUS_ALLOW_PUBLIC_BIND"
bridge_env "NULLCLAW_WEB_TOKEN" "CERBERUS_WEB_TOKEN"
bridge_env "NULLCLAW_GATEWAY_TOKEN" "CERBERUS_GATEWAY_TOKEN"
bridge_env "NULLCLAW_RELAY_TOKEN" "CERBERUS_RELAY_TOKEN"
bridge_env "NULLCLAW_API_KEY" "CERBERUS_API_KEY"
bridge_env "NULLCLAW_OPEN_SKILLS_ENABLED" "CERBERUS_OPEN_SKILLS_ENABLED"
bridge_env "NULLCLAW_OPEN_SKILLS_DIR" "CERBERUS_OPEN_SKILLS_DIR"

if command -v cerberus >/dev/null 2>&1; then
  exec cerberus "$@"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_BIN="$SCRIPT_DIR/../../zig-out/bin/cerberus"
if [[ -x "$LOCAL_BIN" ]]; then
  exec "$LOCAL_BIN" "$@"
fi

echo "cerberus binary not found in PATH or zig-out/bin." >&2
exit 127
EOF
chmod +x "$TARGET_DIR/scripts/compat/nullclaw"

mkdir -p "$TARGET_DIR/reports"
audit_file="$TARGET_DIR/reports/branding-audit.txt"
tmp_hits="$(mktemp)"
grep -RIn \
  --exclude-dir=".git" \
  --exclude-dir="sqlite3" \
  --exclude-dir="reports" \
  --exclude="LICENSE" \
  --exclude="UPSTREAM.md" \
  --exclude="nullclaw" \
  -E "nullclaw|NullClaw|NULLCLAW" "$TARGET_DIR" > "$tmp_hits" || true

{
  echo "Branding audit generated at ${generated_ts}"
  echo "Target: ${TARGET_DIR}"
  echo
  cat "$tmp_hits"
} > "$audit_file"

if [[ -s "$tmp_hits" ]]; then
  warn "Some legacy branding tokens remain (see $audit_file)"
else
  ok "Rebrand complete with no remaining nullclaw tokens in scanned files"
fi
rm -f "$tmp_hits"

ok "Cerberus refactor tree generated at $TARGET_DIR"
printf "Next:\n"
printf "  1) bash %s/scripts/verify_rebrand_integrity.sh --target=%s\n" "$ROOT_DIR" "$TARGET_DIR"
printf "  2) Install Zig 0.15.2 then run: zig build test --summary all\n"
