import os
import json
import sqlite3
import subprocess
import sys
from pathlib import Path

# --- CONFIGURATION REGISTRY ---
# Define every key needed by every vertical in Aura.
VAULT_REGISTRY = {
    "GROQ_API_KEY": {"desc": "Groq Cloud API Key (for fast agent execution)", "required": True},
    "RESEND_API_KEY": {"desc": "Resend API Key (for outreach email dispatch)", "required": True},
    "STRIPE_SECRET_KEY": {"desc": "Stripe Live/Test Secret Key (for payments)", "required": True},
    "STRIPE_WEBHOOK_SECRET": {"desc": "Stripe Webhook Signing Secret (for fulfillment)", "required": True},
    "STRIPE_WEBHOOK_SECRET_THIN": {"desc": "Stripe Webhook Signing Secret (THIN payload destination)", "required": False},
    "OPENAI_MODEL_NAME": {"desc": "Groq/OpenAI Model Name (e.g., llama-3.3-70b-versatile)", "default": "llama-3.3-70b-versatile"},
    "OPENAI_API_BASE": {"desc": "Groq/OpenAI API Base URL", "default": "https://api.groq.com/openai/v1"},
    "N8N_WEBHOOK_URL": {"desc": "URL of your n8n MCP/Gateway webhook", "default": "http://localhost:5678/webhook/mcp-gateway"},
    "OPS_AUTOMATION_WEBHOOK_URL": {"desc": "URL of Aura ops automation webhook (preferred over n8n)", "default": "http://127.0.0.1:9100/ops/stripe"},
    "GEMINI_API_KEY": {"desc": "Google Gemini API Key (for Gemini CLI / gateway)", "required": False},
    "OWNER_EMAIL": {"desc": "Email of the system owner", "default": ""},
    "AURA_VAULT_TOKEN": {"desc": "Secret token for vault-level operations", "required": True},
}

_VAULT_DIR = Path(__file__).resolve().parent
AURA_ROOT = Path(os.environ.get("AURA_HOME", _VAULT_DIR.parent))
VAULT_FILE = _VAULT_DIR / "aura-vault.json"
ENV_TARGETS = [
    AURA_ROOT / "ai_agency_wealth" / ".env",
    Path.home() / ".n8n" / ".env",
]

WEBHOOK_KEYS = [
    "STRIPE_WEBHOOK_SECRET",
    "STRIPE_WEBHOOK_SECRET_THIN",
    "N8N_WEBHOOK_URL",
    "OPS_AUTOMATION_WEBHOOK_URL",
]

def load_vault():
    if not VAULT_FILE.exists():
        return {}
    with open(VAULT_FILE, "r") as f:
        return json.load(f)

def save_vault(data):
    # Write with 0o600 atomically: open with O_CREAT|O_WRONLY and mode 0o600
    fd = os.open(VAULT_FILE, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        json.dump(data, f, indent=4)

def validate_key(name, value):
    """Placeholder for future verification logic (e.g., calling Groq's /models)"""
    if not value or value.startswith("sk_test_placeholder"):
        return False, "Placeholder or empty value."
    return True, "Present"

def bootstrap_vault():
    print("🛡️  AURA SOVEREIGN VAULT BOOTSTRAP 🛡️")
    print("-------------------------------------")
    vault = load_vault()
    updated = False

    for key, info in VAULT_REGISTRY.items():
        default_val = info.get("default", "")
        current_val = vault.get(key, default_val)

        # Persist defaults into the vault so downstream syncs include them.
        if key not in vault and default_val not in (None, ""):
            vault[key] = default_val
            current_val = default_val
            updated = True
        
        if not current_val or current_val == "":
            print(f"\n[MISSING] {key}")
            print(f"Description: {info['desc']}")
            new_val = input(f"Enter {key}: ").strip()
            if new_val:
                vault[key] = new_val
                updated = True
        else:
            print(f"[OK] {key} is already set.")

    if updated:
        save_vault(vault)
        print("\n✅ Vault updated and secured.")
    
    sync_envs(vault)

def sync_envs(vault):
    print("\n🔄 Syncing Vault keys to all Aura service environments...")
    
    # Prepare the .env content
    env_content = "# GENERATED BY AURA VAULT - DO NOT EDIT MANUALLY\n"
    # Emit all known keys (using defaults) so services don't get "None"/"none" models.
    for key, info in VAULT_REGISTRY.items():
        value = vault.get(key)
        if value in (None, ""):
            value = info.get("default", "")
        if value in (None, ""):
            continue
        env_content += f"{key}={value}\n"
    
    # Additional required but non-vault keys
    env_content += "PYTHONPATH=/home/yani/Aura/ai_agency_wealth\n"

    for target in ENV_TARGETS:
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            with open(target, "w") as f:
                f.write(env_content)
            print(f"  - Updated: {target}")
        except Exception as e:
            print(f"  - ❌ Failed to update {target}: {e}")

    print("\n🚀 Restarting continuous services to apply changes...")
    subprocess.run(["sudo", "systemctl", "restart", "ai_pay", "aura_autopilot"], check=False)


def configure_webhooks():
    print("🌐  AURA WEBHOOK CONFIGURATION")
    print("-------------------------------")
    vault = load_vault()
    updated = False

    for key in WEBHOOK_KEYS:
        info = VAULT_REGISTRY.get(key, {"desc": "Webhook-related key"})
        current_val = vault.get(key, info.get("default", ""))

        print(f"\nKey: {key}")
        print(f"Description: {info.get('desc', 'Webhook-related key')}")
        if current_val:
            masked = current_val[:4] + "*" * max(0, len(current_val) - 4)
            print(f"Current value: {masked}")
        else:
            print("Current value: <not set>")

        new_val = input("Enter new value (leave blank to keep current): ").strip()
        if new_val:
            vault[key] = new_val
            updated = True

    if updated:
        save_vault(vault)
        print("\n✅ Webhook settings updated.")
        sync_envs(vault)
    else:
        print("\nNo changes made to webhook settings.")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "sync":
            sync_envs(load_vault())
        elif sys.argv[1] == "webhook":
            configure_webhooks()
        else:
            bootstrap_vault()
    else:
        bootstrap_vault()
