ALTER TABLE merchants ADD COLUMN IF NOT EXISTS plan TEXT DEFAULT 'free';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS plan_active_until TIMESTAMPTZ;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS debtor_limit INTEGER DEFAULT 3;
